apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Andor Homelab
    headerStyle: clean
    layout:
      Monitoring:
        style: row
        columns: 5
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Homelab:
        - GitHub Repo:
            - abbr: GH
              href: https://github.com/kola0031/homelab
  services.yaml: |
    - Monitoring:
        - Grafana:
            href: http://grafana.local
            description: Metrics dashboards
            icon: grafana.png
            widget:
              type: grafana
              url: http://prometheus-grafana.default.svc.cluster.local
              username: admin
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

        - Prometheus:
            href: http://prometheus.local
            description: Metrics collection
            icon: prometheus.png
            widget:
              type: prometheus
              url: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090

    - Utilities:
        - Pi-hole:
            href: http://pihole.local
            description: Network-wide ad blocker
            icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANsAAADmCAMAAABruQABAAABmFBMVEX/////AACYAgAPwA8Nxw0L0AsMzQwOxA4MygyTAAAQuhAOwg4Nxg0D8QMK1AoPvg8F6gUJ1wkRtxEC9wIB+gED8gMG5AYF6wUAAAAC+AII2wgStBKQAAAA/gD/6emcAAD/bGzw3t7/Ly//5ub5/vn/8/P/aWn/urr/DQ3/3Nz/iIj/IyP/dXW0WVn/7u71/fWw7rDc/dzs7Oz/srL/YmL/kZHv29v/RUX/qKiQ3pCQ15Db9tt72Xvt/O3G/cbf+99i6GLNzc14eHjb29ujo6P/Pj7/UlL/x8edKimeExKoPDvhwcH/np7/09O4ZWXWqanCh4f4FRUsvCxGw0a257ZTwlNoz2hvyG9/2n/I8Mik3qQ8zjxT1VMmuCaT5JNr3GtI3Ui0/bSm/aa88ryN+41T+VNh1GFW9lbV/9UyzzKk76R+/35573nB/sFk7GSv/q845jjBwcEgICBBQUFlZWUwMDCGhoZMTEynp6fUUlLEdnWxAADOEhLeDAu+IiG4LS3Xr6/dc3PWjIzKSEioNTTiMzOXHBqxHBsPwAJ3AAAO+klEQVR4nN2diVsTRx/HN1GOBSSAchhWA5FAuJFDohClIAkBRPGgchQQlFpKrb1oK8fLa33x335n9shes7szs7NXvz6PD48ku/PJ75wjK8fhqAv8+Zeq67v2pvbnz1+8Wrv/4OVUfvhfBfqqvb29qampRlSi5sXag/V80GNipW/b2yU6kS8BdWVzbWMq6HGx0P0ym2w6CAd1/27QQ3OtB1qzSWyQrBao7vV60KNzpw2D3WS42tqqqrqqqs2RKAffS7RPQjZAd7Xu6nR0Q28KaTbokxIc0FZU6fKW8SayQbjqqzvR9Mzh7xS2Jj1blWK3aqjt4aAHSqNXTUa7aeKtToarrK7eD3qgFPrWIpfUKi4pGq6ysnInev3YhimZXLmiSZSKUwK4ishV8ym7GlBXp2Wr3A56sISaatIlSh1bldYnAVzFVrRSStd31vGm5slqia3ih2hVA32iTCRqriDsprBVVESqkG/oakBN4vlawlC7VZ+sqKivj1IDPWX0yZq1RC0ql0h2ixZck4HtSmJtsxZRAyQ2ABchtwQBZ8gltdObcryZfBKg1ddHJ6FsIHrl6S19nqzUwVVEphRM6XOJBLe2o+u5tMkEaDcy/ddz1DxgZ9raJ+vrd2ju8+j9+zd7UG/8s/sD8zwAwB1sa/Kkka2RcFow/PDtu9abN6BuAfnXmU6h56YH9+v0PVelhq2RIJ/k995dB5LQRDgfu+4XNUY2sTE5ODT1XCrbLua1h3/6vrm5WWS7WWZ77yWNXhsW/eTWiEUuaQTCmhQM71271iyzXb8RBFu+xpgn5bnp1v7VanS8ATmX8K69Vg1aMHbjXtWY8qRY365urldXm/oSmW3G6aoPAZmIJrOV0W498oFJ0brlOtfmVB063oDsG8vhHyGaBu6mmid9bWyeW66XbOZ/sLBb8qPdFR82SGhINl/7mpeG9RJNr7yV30THW2PjofUF91plNBHuur4GNPvb1tTUIOwm9SVbw1totmTS8vN/29raarJbme2dn2RiGUDkSchWXb3FHaB8EsBZGe5Dq57NkEt+9BWN66pB1QC55zrgdtB2Q0dc1/cNGrZrzaba/cZfNm7DEG+69ZID7jUq3pJJZFs509DQoEcz+KSfJQCq67m+V67SzXF2uG2U3ZK7iCu9ldDMPqnkyeu+T//WLfKkvNmhh1PsljR3vW8a7Nlu3PrebzTYnGjjzbCGV33IHRrZAFryyHiVhy0ObLdu/eQ/W944D9CvBe1zhwi2pKFU5UU0I5u+dgex3HLfbDft3PSuCFdvYDNkk6MWa7sF55JALxL6flI3766oyHMjpnhLzuiu8L6lwcEnA3FJoHxCXVLQ75uKcNXDAE6DJhlOl/QaWpzsdutGIGigrUwgei51/rbbpYcT2UY07z+S0ezize/CXdaawW6GNfMdjhsxsn1Q3323xZmtOSg0brgmgdyjUnrl1xKc1ieTatr70NLi6JM/B8Ymhpz13mJFxb4WTmIrT1Hft1ixqXbzeQqg15Rc3yz2A+BGx6EOLbmnvPWDytZgNccJds/8pXUugfoB5MXtei2bEnCPkGj6ecDbQNE47kHCXN808ze4XL6tZVMC7sjAhvDJa4GCQd2He4u1qDwplm6Y9Ke1bJKfdbW0OPjkzRt+T24QepAwzgN0e1TQTjumgDt0Yrt+82GwWJI27OxWvwtfcqSySXOBj45se3a39E8vrWqACCcul8+UfVJcWbirQ0Ox+bxKYq31cg1ALCs3wgjr2lXYWmBL+dpkNgNbaNBAEd+09Ml6aRNn+KMCB1NE2SUtaneI0ICm0TVA7CfFBjmvsI2Ui5vWcLq1oKALm1H7V039pGK4RnFmc1dm29ZkSXQ/GcyczU75LXNfIrNNiy/YLyfKGb3Z9LnkWihPJ+6j7aYYjtuWE+Vwi43dPoT0VMPwDtpuja+l3x+JiVKtAGa7XQtFxUZragu9/yYZrktMlty2OZXIbEfhPmezjtzHkfc5xGSpCTe93T6EMtJ0kuj0+zgz8u9GYIFLtqAM9063rz36zZz/I8fR1HSFga28lgBCbt/IBsl+1Nnsl1/bgGZHAxi7s7pGtvTrysoCF+hPZkxm+7inXz2ebfsF/D032/aN7wPHU37koF5lm1b+eT2Z1KN9fGsMs8e/js7NzQGj/dIWTstB5fdf78pLQep5NZ3ZZn5+ZKpno21zXNtvv7X9Dgw46+t4SdW1frizqz1fkpfttrv3Bj2zfvwnx0GDAY+ca/NplG6U12CMjOy/f2RTyI4fA6650cciX0izJa1mIdsfbb9CrH8b2/Es9Mk5mCRHo+CTinqLuYFCYX5+slCY6CmiXwODDPgjTJJ//eHv8Kg1lOuOGbQ68QTxwj9nuT9ArP3+eDS0BU6nTK5gBFPw7hlfO9ompf65tmPfx0muOxNZNBlU9m8j3ejvbbOPj/9s+yuQwRIp02cNZkE3d3x8/Fd4m5KyxmxspujsU9CjpFHGIs6MOlkKeqTEKmIYTYZ7FvRYCZXDJQM6HcwEPVwSOSURA9xChOA6iNBi2ZN4Z9BDxtUAGRqAS5UiAkeMBpoUIRpwFGgg5ITUUNADdxZhrMnKpvjww9GhgQaFj6dC7pZUDikZLh4Pd8xRo4mGCzUcrUOKikOFNubG3aDFTnkIF1LLubIarHGQLZxu6SLWJKXiYYVzaTWgE9EpQ1gKTEtZ5DqT2EIXcwzQ5IALneXcOyRUXFGYYo4NmpxMwuWWjNBiJypbWIq4u5KtZeNVtnDEHCur6dlCEXPs0OSuKzxwDNEMbIG7JbNYgzrRswWcLVmU7LKy50a2IC3H0iFBX/IfI1uAMccWLZZeNKIFZzmmDgnZBs1sAcUc0zQCNX6JYgvCcowdEignoNjiJdO+ePTQYk9NqSSYhOIBWsGKzeeYYx5rQD2INBkAHOsMKSqDDjcpofgWcx44ZCw2sWTpkj7GnCdosQyyuqmW8wXOE4eMTXB2ZvMp5rxII6An4S6c2Ly3nNYhs6vp9HyhUEi7Zyty9i4pxpzHCaVDoTo7P0mVSpeXC4uLg5+e9oz1uQLs4zod0bx2SzHWsmfnKR6ofEvw8+LTzszYJC3aJMc9c3JJr+HGocVOBQExDl5YXOIyOSo8gMYt4KB5CAestnqOApME6bjeiX5StPkMx9kWN428KuIdgIy3HQO/Aj7XTA/mCTxZBXjgyTmTKPIEbiB2VnL6dPn4BXxpL8FeXAd8Q6dNv2WQF0c1+mKnOAMQpMOemWXMM4Y94ss/YbqkKOYH25Zj53ifLb8ivwPHNbslI2RI0PhFxmhPzIuHlvceVN7U27dqS1ZQDtJbz9yQN2B7DjjTj42msRzMK9YtWof6FQHkQonNDS5YsnWfEnmN9pRuJofCm8xpoga3AKhiWOaKZ2R35w3nq5/kCmrV65+c6NGnA/wCoFx/kGOmedKbl8y57M6TYk9uufik1/Sbe8RmiwvMDq
            widget:
              type: pihole
              url: http://pihole-web.pihole.svc.cluster.local:80
              version: 6
              key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"  
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "andor-cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
  proxies.yaml: ""
  proxmox.yaml: ""
