apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Andor Homelab
    headerStyle: clean
    layout:
      Monitoring:
        style: row
        columns: 1
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Homelab:
        - GitHub Repo:
            - abbr: GH
              href: https://github.com/kola0031/homelab
  services.yaml: |
    - Monitoring:
        - Grafana:
            href: http://grafana.local
            description: Metrics dashboards
            icon: grafana.png
            widget:
              type: grafana
              url: http://prometheus-grafana.default.svc.cluster.local
              username: admin
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

        - Prometheus:
            href: http://prometheus.local
            description: Metrics collection
            icon: prometheus.png
            widget:
              type: prometheus
              url: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090

    - Utilities:
        - Pi-hole:
            href: http://pihole.local
            description: Network-wide ad blocker
            icon: pihole.png
            widget:
              type: pihole
              url: http://pihole-web.pihole.svc.cluster.local:80
              version: 6
              key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"  
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "andor-cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
  proxies.yaml: ""
  proxmox.yaml: ""
