apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- infrastructure-crds.yaml
- infrastructure-networking.yaml
- apps.yaml
- infrastructure-envoy-gateway.yaml
- infrastructure-monitoring.yaml
